stages:
  sisu:
    cmd: >-
      poetry run python ./ufba_data_analysis/sisu/sisu.py
      -d ./data/raw/sisu
      -o ./data/interim/sisu/sisu_ufba_enrolled.parquet
      --cfg conf/sisu/process1.yaml
    deps:
      - ./ufba_data_analysis/sisu/sisu.py
      - ./data/raw/sisu
      - conf/sisu/process1.yaml
    outs:
      - ./data/interim/sisu/sisu_ufba_enrolled.parquet
  fa:
    cmd: >-
      poetry run python ./ufba_data_analysis/sisu/fa.py
      -i ./data/interim/sisu/sisu_ufba_enrolled.parquet
      -o ./data/interim/sisu_with_nse/sisu_ufba_enrolled_with_nse.parquet
    deps:
      - ./ufba_data_analysis/sisu/fa.py
      - ./data/interim/sisu/sisu_ufba_enrolled.parquet
    params:
      - factor_analysis.max_iter
      - factor_analysis.nse_cols
      - factor_analysis.n_factors
    outs:
      - ./data/interim/sisu_with_nse/sisu_ufba_enrolled_with_nse.parquet